version: "2"

services:

  deploy:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - "AWS_ACCESS_KEY_ID=${DEV_DEPLOY_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${DEV_DEPLOY_AWS_SECRET_ACCESS_KEY}"
      - "CLOUDFORMATION_ROLE_ARN=${DEV_CLOUDFORMATION_ROLE_ARN}"
      - "LAMBDA_EXECUTION_ROLE_ARN=${DEV_LAMBDA_EXECUTION_ROLE_ARN}"
      - "KEBOOLA_STACK=${DEV_KEBOOLA_STACK}"
      - "REGION=${DEV_REGION}"
      - "SERVICE_NAME=${DEV_SERVICE_NAME}"
      - "STAGE=dev"
    command: >
             sh -c '
             serverless deploy
             '

  test-unit:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - "AWS_ACCESS_KEY_ID=accessKey"
      - "AWS_SECRET_ACCESS_KEY=secretKey"
      - "REGION=us-east-1"
    command: >
             sh -c '
             yarn test:unit
             '

  test-func:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - "API_ENDPOINT=${DEV_API_ENDPOINT}"
      - "AWS_ACCESS_KEY_ID=${DEV_TEST_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${DEV_TEST_AWS_SECRET_ACCESS_KEY}"
      - "REGION=${DEV_REGION}"
      - "SERVICE_NAME=${DEV_SERVICE_NAME}"
      - "STAGE=dev"
    command: >
             sh -c '
             yarn test:func
             '
