version: "2"

services:

  deploy:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - "AWS_ACCESS_KEY_ID=${DEV_DEPLOY_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${DEV_DEPLOY_AWS_SECRET_ACCESS_KEY}"
      - "KEBOOLA_STACK=${DEV_KEBOOLA_STACK}"
      - "PAPERTRAIL_PORT=${DEV_PAPERTRAIL_PORT}"
      - "REGION=${DEV_REGION}"
      - "SERVICE_NAME=${DEV_SERVICE_NAME}"
      - "STAGE=dev"
    command: >
             sh -c '
             serverless deploy
             '

  test-unit:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - "AWS_ACCESS_KEY_ID=accessKey"
      - "AWS_SECRET_ACCESS_KEY=secretKey"
      - "REGION=us-east-1"
    command: >
             sh -c '
             ./node_modules/.bin/mocha --timeout 0 --require babel-register --require source-map-support test/unit
             '

  test-func:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - "API_ENDPOINT=${DEV_API_ENDPOINT}"
      - "AWS_ACCESS_KEY_ID=${DEV_TEST_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${DEV_TEST_AWS_SECRET_ACCESS_KEY}"
      - "REGION=${DEV_REGION}"
      - "SERVICE_NAME=${DEV_SERVICE_NAME}"
      - "STAGE=dev"
    command: >
             sh -c '
             ./node_modules/.bin/mocha --timeout 0 --require babel-register --require source-map-support test/func
             '
