version: "2"

services:
  app:
    image: keboola/serverless-demo-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code:cached
    working_dir: /code
    environment:
      - "CLOUDFORMATION_ROLE_ARN=dummyArn"
      - "LAMBDA_EXECUTION_ROLE_ARN=dummyArn"
      - "KEBOOLA_STACK_TAG=serverless-demo-app"
      - "REGION=us-east-1"
      - "SERVICE_NAME=dev-serverless-demo-app"
      - "STAGE=dev"

  deploy:
    image: keboola/serverless-demo-app
    volumes:
      - .:/code:cached
    working_dir: /code
    environment:
      - "AWS_ACCESS_KEY_ID=${DEV_DEPLOY_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${DEV_DEPLOY_AWS_SECRET_ACCESS_KEY}"
      - "CLOUDFORMATION_ROLE_ARN=${DEV_CLOUDFORMATION_ROLE_ARN}"
      - "LAMBDA_EXECUTION_ROLE_ARN=${DEV_LAMBDA_EXECUTION_ROLE_ARN}"
      - "KEBOOLA_STACK_TAG=${DEV_KEBOOLA_STACK_TAG}"
      - "REGION=${DEV_REGION}"
      - "SERVICE_NAME=${DEV_SERVICE_NAME}"
      - "STAGE=${DEV_STAGE}"
    command: serverless deploy --force

  test-unit:
    image: keboola/serverless-demo-app
    volumes:
      - .:/code:cached
    working_dir: /code
    environment:
      - "AWS_ACCESS_KEY_ID=accessKey"
      - "AWS_SECRET_ACCESS_KEY=secretKey"
      - "REGION=us-east-1"
    command: yarn test:unit

  test-func:
    image: keboola/serverless-demo-app
    volumes:
      - .:/code:cached
    working_dir: /code
    environment:
      - "API_ENDPOINT=${TEST_API_ENDPOINT}"
      - "AWS_ACCESS_KEY_ID=${TEST_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${TEST_AWS_SECRET_ACCESS_KEY}"
      - "REGION=${DEV_REGION}"
      - "SERVICE_NAME=${DEV_SERVICE_NAME}"
      - "STAGE=${DEV_STAGE}"
    command: yarn test:func
